### ISSUE TITLE
Allow the players to choose a map size at the start

### ISSUE THREAD

**Issue by polltery** [polltery/node-cli-game-example#16]
After the players select the number of players, allow them to choose a map size by manually inputting `mapHeight` and `mapWidth`, default will be under `config.js`.

**Comment by pedramp** [comment]
working on it.
I'll submit my PR soon.

**Comment by pedramp** [comment]
@polltery my PR submitted.  #23

**Comment by polltery** [comment]
Thanks @pedramp, I will review them and update the PR accordingly!
