### ISSUE TITLE
Add difficulty selection at the start of the game

### ISSUE THREAD

**Issue by polltery** [polltery/node-cli-game-example#27]
We need to add a prompt before the game starts that will allow the players to choose the difficulty. The following difficulties will be allowed..
1. `(E) EASY` : Player gets 25 POWER at the start
2. `(M) MEDIUM` : Player gets 15 POWER at the start
3. `(H) HARD` : Player gets 10 POWER at the start

**Comment by ggangix** [comment]
I would like to work on this task.

**Comment by polltery** [comment]
@ggangix thanks. I'll assign it to you.
